name: Build
on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      tag-name:
        type: string
        default: "draft"
      channel:
        type: string
        default: "dev"

env:
  IS_GITHUB_ACTIONS: 1
  CHANNEL: "${{ inputs.channel }}"
  FLUTTER_VERSION: '3.38.5'
  NDK_VERSION: r28c
  UPLOAD_ARTIFACT: "${{ inputs.upload-artifact }}"
  TAG_NAME: "${{ inputs.tag-name }}"
  TARGET_NAME_gz: "Hiddify-Linux-x64-AppImage.tar"
  TARGET_NAME_AppImage: "Hiddify-Linux-x64-AppImage"
  TARGET_NAME_deb: "Hiddify-Debian-x64"
  # TARGET_NAME_rpm: "Hiddify-rpm-x64"
  TARGET_NAME_apk: "Hiddify-Android"
  TARGET_NAME_aab: "Hiddify-Android"
  TARGET_NAME_exe: "NimHiddify-Windows-Setup-x64"
  TARGET_NAME_msix: "NimHiddify-Windows-x64"
  TARGET_NAME_zip: "NimHiddify-Windows-Portable-x64"
  TARGET_NAME_dmg: "Hiddify-MacOS"
  TARGET_NAME_pkg: "Hiddify-MacOS-Installer"
  TARGET_NAME_ipa: "Hiddify-iOS"
  

jobs:
  test:
    outputs:
      draftBuildCode: ${{ steps.draftBuildCode.outputs.datetime }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2.21.0 #issue with 2.13
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          
      - name: Prepare
        run: make linux-amd64-prepare
      - name: Test
        run: flutter test

      - name: make draftBuildCode
        id: draftBuildCode
        run: echo "::set-output name=datetime::$(date +'%d.%H.%M')"


  build:
    needs: test
    permissions: write-all
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows
            os: windows-latest
            aarch: amd64
            targets: exe,zip

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.21.0 #issue with 2.13
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          # flutter-version-file: pubspec.yaml
          channel: 'stable'
          cache: true

      - name: Setup dependencies
        run: |
          make ${{ matrix.platform }}-install-deps  
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Prepare for ${{ matrix.platform }}
        run: |
          make ${{ matrix.platform }}-prepare


      - name: Build ${{ matrix.platform }}
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          make ${{ matrix.platform }}-release

      - name: Copy to out Windows
        if: matrix.platform == 'windows'
        shell: pwsh
        run: |
          Get-ChildItem -Path dist -Recurse | Select-Object FullName
          New-Item -ItemType Directory -Path "out" -Force | Out-Null
          $targets = "${{ matrix.targets }}".Split(',')
          foreach ($ext in $targets) {
            $ext = $ext.Trim()
            $key = "TARGET_NAME_$ext"
            $targetName = (Get-Item "env:$key").Value
            
            $files = Get-ChildItem -Path dist -Recurse -Filter "*.$ext"
            
            foreach ($file in $files) {
                $destination = Join-Path -Path "out" -ChildPath "$targetName.$ext"
                Move-Item -Path $file.FullName -Destination $destination -Force
            }
          }
          Get-ChildItem -Path out
          
      - name: Upload Artifact
        if: env.UPLOAD_ARTIFACT == 'true'
        uses: actions/upload-artifact@v6
        with:
          name: ${{matrix.platform}}
          path: ./out
          retention-days: 1

  update-draft:
    permissions: write-all
    if: ${{ inputs.upload-artifact }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
      - name: Download Artifact
        uses: actions/download-artifact@v7
        with:
          merge-multiple: true
          pattern: "*"
          path: ./out/
          

      - name: Display Files Structure
        run: ls -R
        working-directory: ./out

      - name: Delete Current Release Assets
        uses: 8Mi-Tech/delete-release-assets-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'draft'
          deleteOnlyFromDrafts: false
          
      - name: prepare_release_message
        continue-on-error: true
        run: |
          set +e 
          sed 's|RELEASE_TAG|${{ env.TAG_NAME }}|g' ./.github/release_message.md > release.md
          pip install gitchangelog pystache mustache markdown
          prelease=$(curl --silent "https://api.github.com/repos/Nim4a/hiddify-app/releases/latest" | grep -Po '"tag_name": "\K([^"]*)') 
          echo -e "\n\n<details markdown=1><summary>All changes from $current to the latest commit:</summary>\n\n">>release.md
          gitchangelog "${prelease}.." >> release.md  2>&1 || echo "Error in gitchangelog"
          echo -e "\n\n</details>">>release.md
      - name: Create or Update Draft Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./out/*
          name: 'draft'
          tag_name: 'draft'
          body_path: './release.md'
          prerelease: true

  upload-release:
    permissions: write-all
    if: ${{ inputs.upload-artifact && inputs.tag-name != 'draft' }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: Download Artifact
        uses: actions/download-artifact@v7
        with:
          merge-multiple: true
          pattern: "*"
          path: ./out/

      - name: Display Files Structure
        run: |
          ls -R ./out
          ls -R ./.github/
          ls -R ./.git/

      - name: prepare_release_message
        run: |
          sed 's|RELEASE_TAG|${{ env.TAG_NAME }}|g' ./.github/release_message.md >> release.md

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # prerelease: ${{ env.CHANNEL == 'dev' }}
          prerelease: true
          tag_name: ${{ env.TAG_NAME }}
          body_path: './release.md'
          files: ./out/*
